Insert Into genel.tb_kitap_tipi (id, kitap_tipi) Values (1,'Anlatı');
Insert Into genel.tb_kitap_tipi (id, kitap_tipi) Values (2,'Hobi Kitapları');
Insert Into genel.tb_kitap_tipi (id, kitap_tipi) Values (3,'Aile (Kadın, Erkek ve Çocuk)');
Insert Into genel.tb_kitap_tipi (id, kitap_tipi) Values (4,'Astroloji-Fal-Rüya Tabirleri');
Insert Into genel.tb_kitap_tipi (id, kitap_tipi) Values (5,'Bilgisayar-İnternet');
Insert Into genel.tb_kitap_tipi (id, kitap_tipi) Values (6,'Biyografi');
Insert Into genel.tb_kitap_tipi (id, kitap_tipi) Values (7,'Çizgi-Roman');
Insert Into genel.tb_kitap_tipi (id, kitap_tipi) Values (8,'Dünya Klasikleri');
Insert Into genel.tb_kitap_tipi (id, kitap_tipi) Values (9,'Dergi');
Insert Into genel.tb_kitap_tipi (id, kitap_tipi) Values (10,'Ders Kitabı');
